import java.util.*;

public class Main {
    public static void main(String[] args) throws Exception {
        test();
        
        String groups = 
            "niujdxegbrtlq\n" + 
            "dxiljmqektnur\n" + 
            "usxdvtphcernzi\n" + 
            "ityruneqdxw\n" + 
            "\n" + 
            "lztnekjhv\n" + 
            "hlvenzktw\n" + 
            "ptknvebzgh\n" + 
            "\n" + 
            "qd\n" + 
            "d\n" + 
            "d\n" + 
            "d\n" + 
            "\n" + 
            "kisncozxytdrmgba\n" + 
            "nmtgdrzspcokyihaqx\n" + 
            "fzlcxiokamtgynsdr\n" + 
            "oxtkasdgcrymnizf\n" + 
            "\n" + 
            "epxj\n" + 
            "aht\n" + 
            "rhujt\n" + 
            "byswqfn\n" + 
            "krzodg\n" + 
            "\n" + 
            "ykxgnhspoqmzujcatdevf\n" + 
            "zmvtlkwnhcyoig\n" + 
            "\n" + 
            "qznfevulkgiwrmcabt\n" + 
            "bqarvcwigmxfe\n" + 
            "hwgcabivferqm\n" + 
            "ivmbgfepcarwq\n" + 
            "\n" + 
            "fotkqlvy\n" + 
            "kfvoy\n" + 
            "ovyfk\n" + 
            "kfoavy\n" + 
            "\n" + 
            "ydwlctuivszbrjp\n" + 
            "yvdzbpsulwrtjic\n" + 
            "rcvisjypzlbudwt\n" + 
            "\n" + 
            "iywfekuzsq\n" + 
            "skiuyefzqw\n" + 
            "\n" + 
            "ozc\n" + 
            "htibp\n" + 
            "wjf\n" + 
            "c\n" + 
            "wf\n" + 
            "\n" + 
            "cstkeihmjz\n" + 
            "kshz\n" + 
            "nhkzfs\n" + 
            "zlfkhsr\n" + 
            "\n" + 
            "fpszrjvml\n" + 
            "erjhbsfmlpg\n" + 
            "rdsvilhepjfw\n" + 
            "fypjqstrulcx\n" + 
            "lafrjesp\n" + 
            "\n" + 
            "rzv\n" + 
            "rq\n" + 
            "v\n" + 
            "xeysd\n" + 
            "\n" + 
            "nb\n" + 
            "nuxb\n" + 
            "npwg\n" + 
            "\n" + 
            "zqeah\n" + 
            "hea\n" + 
            "krpeha\n" + 
            "ehaq\n" + 
            "\n" + 
            "ftzepxdbqs\n" + 
            "fjaydtgixse\n" + 
            "\n" + 
            "lipevfh\n" + 
            "pvfhieo\n" + 
            "hevpfio\n" + 
            "gfcphevi\n" + 
            "\n" + 
            "cobq\n" + 
            "oqcb\n" + 
            "obqc\n" + 
            "cboq\n" + 
            "oqbc\n" + 
            "\n" + 
            "hjdnpv\n" + 
            "ndvwjp\n" + 
            "uvmdxgs\n" + 
            "tjvd\n" + 
            "\n" + 
            "xdratljsfwo\n" + 
            "blnqve\n" + 
            "\n" + 
            "i\n" + 
            "sp\n" + 
            "\n" + 
            "z\n" + 
            "z\n" + 
            "\n" + 
            "j\n" + 
            "oj\n" + 
            "j\n" + 
            "\n" + 
            "zmrosjeivnxult\n" + 
            "pvmdeuosjzngxil\n" + 
            "\n" + 
            "zpcdrbfwmyj\n" + 
            "bmjlprzcfydw\n" + 
            "gwmjbfzrypodc\n" + 
            "pzwrjdbmcyf\n" + 
            "\n" + 
            "mc\n" + 
            "m\n" + 
            "cm\n" + 
            "m\n" + 
            "smnv\n" + 
            "\n" + 
            "ncsfduryqtajovxe\n" + 
            "nqdvocyjretusf\n" + 
            "fsoutcnrjqkegyvd\n" + 
            "fyujnrcoqetsvd\n" + 
            "yvjnstcquoefrid\n" + 
            "\n" + 
            "t\n" + 
            "t\n" + 
            "vt\n" + 
            "\n" + 
            "mvqefnprgbkclajwdzuyos\n" + 
            "aqydogmecfrnkvjublszpw\n" + 
            "egaxlyfqwmjbknzcstrvdopu\n" + 
            "\n" + 
            "qwpfy\n" + 
            "pwub\n" + 
            "pmqwy\n" + 
            "\n" + 
            "akmes\n" + 
            "cqpagks\n" + 
            "sak\n" + 
            "fmksa\n" + 
            "\n" + 
            "lcxfg\n" + 
            "jflac\n" + 
            "izhywvfmcblt\n" + 
            "nflqc\n" + 
            "fsaorlc\n" + 
            "\n" + 
            "kolvd\n" + 
            "zknsoavuh\n" + 
            "kolvy\n" + 
            "\n" + 
            "dxbsoazvfytupi\n" + 
            "esaznmxkwhjirdqofgcl\n" + 
            "\n" + 
            "brcuwftgminxeqdls\n" + 
            "neqafyzwd\n" + 
            "qwdofnaejp\n" + 
            "fvkehnjzwqpd\n" + 
            "\n" + 
            "v\n" + 
            "v\n" + 
            "v\n" + 
            "\n" + 
            "pyg\n" + 
            "gpy\n" + 
            "\n" + 
            "eklcothrxvbifqpmjzs\n" + 
            "pxhzbfjrovumlgktqncw\n" + 
            "kxzqfbjrlchovtpam\n" + 
            "\n" + 
            "qfvdnyhrxigzs\n" + 
            "qixspvhdyrnfg\n" + 
            "yhdqtvsngxfilr\n" + 
            "uxfhbsrqiyvngdj\n" + 
            "nfryhxpqvditsg\n" + 
            "\n" + 
            "leqashvcmwdbrkjnpyof\n" + 
            "ljkvqinmybfwsgcoaehrp\n" + 
            "\n" + 
            "ju\n" + 
            "uj\n" + 
            "uj\n" + 
            "ju\n" + 
            "\n" + 
            "qukevfbcndxj\n" + 
            "tcoiyqfwlsvndg\n" + 
            "\n" + 
            "hero\n" + 
            "orhe\n" + 
            "rheo\n" + 
            "\n" + 
            "m\n" + 
            "m\n" + 
            "m\n" + 
            "m\n" + 
            "\n" + 
            "plkvnsri\n" + 
            "psvklnri\n" + 
            "\n" + 
            "tjluwary\n" + 
            "wydqtlijoa\n" + 
            "shwzlajty\n" + 
            "tyalwnj\n" + 
            "valjyowt\n" + 
            "\n" + 
            "oukeqfmlvyxsh\n" + 
            "spkluqxibmn\n" + 
            "uqlskmbx\n" + 
            "\n" + 
            "uagyjmfi\n" + 
            "uijfaymg\n" + 
            "\n" + 
            "vkbejxhnqpomuigcrdlyawsz\n" + 
            "nhbkwpygjzxvoiursqeldmca\n" + 
            "msruwzndvjoylaqgicehbpxfk\n" + 
            "sceldwiobrnhqvpgmakutzjyx\n" + 
            "\n" + 
            "my\n" + 
            "qdsi\n" + 
            "\n" + 
            "fyxielsvdzojqhurc\n" + 
            "vqyhwofldxisunj\n" + 
            "ovqjxyislnhdfu\n" + 
            "yxduvwhqfonlisj\n" + 
            "hifoyqdsgvxjltu\n" + 
            "\n" + 
            "azqbsoeg\n" + 
            "ozsaeqbg\n" + 
            "qszeaogb\n" + 
            "sbqgzoeaxp\n" + 
            "\n" + 
            "adwpkrqhvtub\n" + 
            "uzbteshfdarvwijlny\n" + 
            "\n" + 
            "pmh\n" + 
            "hubngkiz\n" + 
            "rvhq\n" + 
            "mhp\n" + 
            "\n" + 
            "f\n" + 
            "fpu\n" + 
            "ofs\n" + 
            "rgd\n" + 
            "su\n" + 
            "\n" + 
            "o\n" + 
            "r\n" + 
            "r\n" + 
            "r\n" + 
            "\n" + 
            "wda\n" + 
            "daw\n" + 
            "dwa\n" + 
            "wad\n" + 
            "wad\n" + 
            "\n" + 
            "ehxlvpjk\n" + 
            "mlfkpvxzdh\n" + 
            "\n" + 
            "nbitghoyce\n" + 
            "tcino\n" + 
            "wncojti\n" + 
            "tncois\n" + 
            "\n" + 
            "o\n" + 
            "o\n" + 
            "a\n" + 
            "e\n" + 
            "\n" + 
            "kjbc\n" + 
            "bjcm\n" + 
            "jbc\n" + 
            "\n" + 
            "j\n" + 
            "j\n" + 
            "j\n" + 
            "m\n" + 
            "\n" + 
            "zadkeciyblfhqrpwtogsuxvj\n" + 
            "stykicepvnahjfuqwbordzx\n" + 
            "exbrcpyihqvdkajoztwsfu\n" + 
            "xweohfzdrkpqjycsvtauib\n" + 
            "\n" + 
            "at\n" + 
            "tr\n" + 
            "t\n" + 
            "t\n" + 
            "t\n" + 
            "\n" + 
            "udweol\n" + 
            "oldmsfjaqueb\n" + 
            "xleduo\n" + 
            "oeuhnlxkd\n" + 
            "\n" + 
            "rdiywgmfhu\n" + 
            "difuwghymq\n" + 
            "iyhwgfdmru\n" + 
            "wgdifmyhu\n" + 
            "ugfmhiydaw\n" + 
            "\n" + 
            "ysvcatfqzgwmo\n" + 
            "mszowbhlyaqp\n" + 
            "wrzqoumaysp\n" + 
            "\n" + 
            "nbxkpasv\n" + 
            "svbpxnak\n" + 
            "pbskxvan\n" + 
            "pxkbsnva\n" + 
            "npbsvkax\n" + 
            "\n" + 
            "uwjrbcpkfis\n" + 
            "cbuirlskwz\n" + 
            "sbwqrukic\n" + 
            "suicbwkr\n" + 
            "\n" + 
            "nxiga\n" + 
            "q\n" + 
            "qe\n" + 
            "q\n" + 
            "eq\n" + 
            "\n" + 
            "vipursexkjbwfcyqmgh\n" + 
            "xiuynjdoghwbftrqpcasvemk\n" + 
            "rigxewkzubsqpfchyjmv\n" + 
            "\n" + 
            "x\n" + 
            "n\n" + 
            "\n" + 
            "sjpcqdkyliuoza\n" + 
            "tuokqipsjaldezc\n" + 
            "\n" + 
            "nzovdqs\n" + 
            "qdsonzv\n" + 
            "zvnosqd\n" + 
            "\n" + 
            "lkdrmouxtvegwcqfz\n" + 
            "gdmculwk\n" + 
            "wmgcldku\n" + 
            "kpwgdmclu\n" + 
            "dckpmwgul\n" + 
            "\n" + 
            "jqrpk\n" + 
            "pqk\n" + 
            "pkq\n" + 
            "pqbk\n" + 
            "pqkrz\n" + 
            "\n" + 
            "rdviwqbjlukxhaypgtszonm\n" + 
            "vzmbsorjxatgikyuqnwhld\n" + 
            "\n" + 
            "sixeod\n" + 
            "sdqoim\n" + 
            "folwnjdcuy\n" + 
            "qhdpbxo\n" + 
            "\n" + 
            "cebiw\n" + 
            "wbigz\n" + 
            "pbor\n" + 
            "tbhqsk\n" + 
            "ibwp\n" + 
            "\n" + 
            "tryckpgdzhxsiqmweulbn\n" + 
            "zmrilbcufaetg\n" + 
            "izoculvjbrgtem\n" + 
            "\n" + 
            "dsrn\n" + 
            "bvi\n" + 
            "\n" + 
            "zlaqw\n" + 
            "qwazlj\n" + 
            "qlawz\n" + 
            "\n" + 
            "utjfancdvs\n" + 
            "sutfjkvacnd\n" + 
            "\n" + 
            "igfkzmawp\n" + 
            "zgpekaf\n" + 
            "fgeklpnza\n" + 
            "kpagfcnz\n" + 
            "agzekfp\n" + 
            "\n" + 
            "talbvi\n" + 
            "ivxtoblh\n" + 
            "lvubitp\n" + 
            "ibxklvr\n" + 
            "nbsidfcgyzwmjqvel\n" + 
            "\n" + 
            "nzbkde\n" + 
            "bzl\n" + 
            "bz\n" + 
            "\n" + 
            "zpgxrmiflb\n" + 
            "fymbglpixdzr\n" + 
            "plrxizgmbf\n" + 
            "plrixmzgfb\n" + 
            "lgusepbzrinfaxm\n" + 
            "\n" + 
            "p\n" + 
            "f\n" + 
            "\n" + 
            "bjixd\n" + 
            "zeb\n" + 
            "\n" + 
            "oux\n" + 
            "oua\n" + 
            "suc\n" + 
            "ou\n" + 
            "u\n" + 
            "\n" + 
            "bqdnwlhe\n" + 
            "bqdne\n" + 
            "bnedq\n" + 
            "anvbdueq\n" + 
            "\n" + 
            "gbsftqnrwoiumjx\n" + 
            "wbnuqtfsrjmg\n" + 
            "udqjmrbswtfgn\n" + 
            "wbrmuqnfjgste\n" + 
            "sngfbudzmjqrtw\n" + 
            "\n" + 
            "axcnkwrjiehbufo\n" + 
            "uaiokcrwjfxhnbe\n" + 
            "pxnkjibcofeuwrah\n" + 
            "ijofewbhnxcaruk\n" + 
            "hjebfxiokanrwuc\n" + 
            "\n" + 
            "vuteoyplzcfhainkb\n" + 
            "xufblscgomnqakztvper\n" + 
            "\n" + 
            "uhrnfxmteckoyidgvwazpbsj\n" + 
            "oxcmhjbeyrfdkngsapzviwut\n" + 
            "xgzvwypabfjrusidhtoenckm\n" + 
            "\n" + 
            "kiulbrnemxhop\n" + 
            "xkprthnmuebo\n" + 
            "ekbhpuoxrmqn\n" + 
            "rmkxphoeunb\n" + 
            "xkhpeonbumr\n" + 
            "\n" + 
            "dnlqsycbr\n" + 
            "nybthvpzx\n" + 
            "bfyacojnu\n" + 
            "lnbygie\n" + 
            "\n" + 
            "gkrtqy\n" + 
            "ygro\n" + 
            "yrq\n" + 
            "ikyrb\n" + 
            "nprdswyal\n" + 
            "\n" + 
            "jwynpe\n" + 
            "jtgynpk\n" + 
            "pgnjyd\n" + 
            "\n" + 
            "pcaitklqf\n" + 
            "dcmqlybjxhz\n" + 
            "claewqouvgr\n" + 
            "\n" + 
            "lf\n" + 
            "f\n" + 
            "fvm\n" + 
            "\n" + 
            "e\n" + 
            "xwv\n" + 
            "e\n" + 
            "\n" + 
            "jzardivtcbwyeouql\n" + 
            "vztrqguyajsiwebf\n" + 
            "ujivbftrezyqaw\n" + 
            "\n" + 
            "olkbngzjimdquxwpre\n" + 
            "gwkqpuesbnoljdvmi\n" + 
            "iqapouwklnejgcbdm\n" + 
            "\n" + 
            "rtxaudofy\n" + 
            "uyajfodrtiqx\n" + 
            "aofyduxrt\n" + 
            "rtudxfazoy\n" + 
            "uoaxfrtdy\n" + 
            "\n" + 
            "czbpfwykrjg\n" + 
            "irfzjy\n" + 
            "zrjyf\n" + 
            "riytzjflu\n" + 
            "mrzyfqj\n" + 
            "\n" + 
            "mbofeiuxzqdyhgapnwsrtcljk\n" + 
            "muxbetdiokvhaljqnsyczp\n" + 
            "bydjaueqsthoikcxzlpnm\n" + 
            "\n" + 
            "orlwpyeutq\n" + 
            "optunreqy\n" + 
            "yrhqunpoktem\n" + 
            "\n" + 
            "frds\n" + 
            "nrslf\n" + 
            "\n" + 
            "lizrxstdyufqb\n" + 
            "gestfvczhrmyu\n" + 
            "\n" + 
            "svtjl\n" + 
            "stlj\n" + 
            "\n" + 
            "dbls\n" + 
            "bdl\n" + 
            "lbd\n" + 
            "\n" + 
            "qjkc\n" + 
            "jcq\n" + 
            "jrq\n" + 
            "lqjy\n" + 
            "jq\n" + 
            "\n" + 
            "dlrfvcmts\n" + 
            "edfnalhrzvwg\n" + 
            "dlturfvosc\n" + 
            "yvfrljixkpd\n" + 
            "lrfbducqv\n" + 
            "\n" + 
            "mpgcdbe\n" + 
            "atkbxhe\n" + 
            "\n" + 
            "p\n" + 
            "pmb\n" + 
            "ps\n" + 
            "\n" + 
            "boumzsvqgwxjcpiek\n" + 
            "emvozpykwbcg\n" + 
            "\n" + 
            "wnfehlygkpbaurxvqtcms\n" + 
            "sykexwmrtagpcuqbhflv\n" + 
            "atuskmelhxvgwqrpjyfcb\n" + 
            "fmlaqepckwrsvbhxyugtd\n" + 
            "hfmupqytbeskxlwvdargc\n" + 
            "\n" + 
            "mvwinotydu\n" + 
            "awjoik\n" + 
            "hqgpiwosclr\n" + 
            "towimv\n" + 
            "eiwzxbo\n" + 
            "\n" + 
            "eqhdijcfgxun\n" + 
            "kbmdopzytunfcxaiqjg\n" + 
            "wuvqcigjndsxlf\n" + 
            "dcxefgqijnu\n" + 
            "\n" + 
            "u\n" + 
            "ur\n" + 
            "uhvfn\n" + 
            "\n" + 
            "ulyfczsqobga\n" + 
            "cogblfzuyaqs\n" + 
            "azyocguqslfb\n" + 
            "\n" + 
            "scfigd\n" + 
            "mw\n" + 
            "w\n" + 
            "\n" + 
            "twlv\n" + 
            "wlvt\n" + 
            "wltvx\n" + 
            "twvl\n" + 
            "stvwl\n" + 
            "\n" + 
            "ejlnxtcws\n" + 
            "lsrbj\n" + 
            "\n" + 
            "mcrhpskeyodtjqvzxi\n" + 
            "dzmrqoivjyefcx\n" + 
            "eiqrxvyldomzjnca\n" + 
            "\n" + 
            "sfzutnm\n" + 
            "ufzmstyn\n" + 
            "yditmnusz\n" + 
            "mlstauchwpen\n" + 
            "\n" + 
            "otxyje\n" + 
            "tin\n" + 
            "amvfgt\n" + 
            "nliot\n" + 
            "tzx\n" + 
            "\n" + 
            "oujcedb\n" + 
            "oudbej\n" + 
            "\n" + 
            "wiprexjbc\n" + 
            "elmangzqjdc\n" + 
            "ecjhta\n" + 
            "jec\n" + 
            "fjvec\n" + 
            "\n" + 
            "xvtkmiphanoesgd\n" + 
            "temkadnvixgofp\n" + 
            "xgodmtalikjvnpqewyz\n" + 
            "fdivepaxnomktgs\n" + 
            "\n" + 
            "rgjzbuaodhmxspnw\n" + 
            "rzubhjoatymdnpgwx\n" + 
            "grbxwpzanmhdju\n" + 
            "dgpecwbuzxjavmlrnhfk\n" + 
            "jgidnpzhxwbrauqms\n" + 
            "\n" + 
            "ryhaxcejou\n" + 
            "hajeucor\n" + 
            "\n" + 
            "pfkryv\n" + 
            "kiptrvfy\n" + 
            "kvrmypf\n" + 
            "pkfvyrw\n" + 
            "pbrvfky\n" + 
            "\n" + 
            "qakjudvm\n" + 
            "scnmlzqie\n" + 
            "ukxmqg\n" + 
            "thfomqpr\n" + 
            "\n" + 
            "enxzagtmjwpb\n" + 
            "pmgytnahjbe\n" + 
            "jtgnbmepa\n" + 
            "\n" + 
            "to\n" + 
            "ots\n" + 
            "ot\n" + 
            "\n" + 
            "juxdrt\n" + 
            "twrulsdj\n" + 
            "\n" + 
            "sthd\n" + 
            "dh\n" + 
            "dh\n" + 
            "\n" + 
            "qy\n" + 
            "rwfieo\n" + 
            "qsy\n" + 
            "k\n" + 
            "bs\n" + 
            "\n" + 
            "gvjfolkhpwtu\n" + 
            "fuvdbohplw\n" + 
            "ifvslwxuphoyenr\n" + 
            "vhpbguwlfo\n" + 
            "kwchpjmzofvlqu\n" + 
            "\n" + 
            "y\n" + 
            "y\n" + 
            "y\n" + 
            "\n" + 
            "thd\n" + 
            "ht\n" + 
            "\n" + 
            "nsua\n" + 
            "btg\n" + 
            "\n" + 
            "vqtum\n" + 
            "gkwl\n" + 
            "\n" + 
            "ewjqaksodiyrf\n" + 
            "pnzmbtvlhgcxu\n" + 
            "\n" + 
            "ocblfapizwuegtyd\n" + 
            "bgnazciskftyoq\n" + 
            "vgybojcaxstzifmn\n" + 
            "\n" + 
            "d\n" + 
            "s\n" + 
            "d\n" + 
            "d\n" + 
            "d\n" + 
            "\n" + 
            "iuwzvkhjabplnf\n" + 
            "kziaulnwjpfvbh\n" + 
            "kvjawunhilzfbp\n" + 
            "zbwanklufiyjvph\n" + 
            "\n" + 
            "ck\n" + 
            "p\n" + 
            "l\n" + 
            "\n" + 
            "mb\n" + 
            "m\n" + 
            "mo\n" + 
            "om\n" + 
            "iumqkl\n" + 
            "\n" + 
            "bwikmgvqojtrhulpyedxfnas\n" + 
            "kvohbytnrgdmilqeupaxfjw\n" + 
            "\n" + 
            "rcomsupn\n" + 
            "bef\n" + 
            "ykie\n" + 
            "iethf\n" + 
            "\n" + 
            "gscf\n" + 
            "myaw\n" + 
            "\n" + 
            "kcxd\n" + 
            "ydekocq\n" + 
            "\n" + 
            "rqjiyzew\n" + 
            "jielwnrqzy\n" + 
            "qijwzyer\n" + 
            "ezqywjir\n" + 
            "\n" + 
            "qfgxmzuip\n" + 
            "uiqzgpmfx\n" + 
            "gufxmizpq\n" + 
            "hufxpzrmqgi\n" + 
            "\n" + 
            "tiywmjbacosku\n" + 
            "bdkmoutzjayc\n" + 
            "jaycpvmboukt\n" + 
            "\n" + 
            "qyrgcpkudtlzsewoah\n" + 
            "wcksorpgtqdfiunhza\n" + 
            "ukotcshxvazrqgwpd\n" + 
            "hpwoscgazrdkqut\n" + 
            "hadyerwkmtgpsuoqcz\n" + 
            "\n" + 
            "zikjumvr\n" + 
            "bxlowe\n" + 
            "\n" + 
            "ljqephm\n" + 
            "qjgaphe\n" + 
            "jhq\n" + 
            "hqjtc\n" + 
            "jqrsmeh\n" + 
            "\n" + 
            "sixjyuqznhlta\n" + 
            "yqxalisnhzju\n" + 
            "ujasnzxyeivlhq\n" + 
            "\n" + 
            "ihtcar\n" + 
            "ihgdx\n" + 
            "\n" + 
            "sbdohyvz\n" + 
            "fxqc\n" + 
            "\n" + 
            "qrdmuhstefolwjckgy\n" + 
            "utviejwsgzoqkl\n" + 
            "\n" + 
            "sgdqtweo\n" + 
            "ywuzhojd\n" + 
            "\n" + 
            "jlgfzqwdp\n" + 
            "bgevujxykdipon\n" + 
            "\n" + 
            "nojcgx\n" + 
            "oxc\n" + 
            "ofcx\n" + 
            "\n" + 
            "dhrvawzgsikqjuyepx\n" + 
            "cwrqpkgyxzedmjhbtauv\n" + 
            "wdvurxqahpkgjenyz\n" + 
            "\n" + 
            "hkyiewspzavotgbcfxn\n" + 
            "oesrzbdtyxwipkvahgcqnf\n" + 
            "gatpwnfxzybokhsicve\n" + 
            "\n" + 
            "ezfgqovsmr\n" + 
            "ij\n" + 
            "nk\n" + 
            "lijut\n" + 
            "jtw\n" + 
            "\n" + 
            "nb\n" + 
            "nb\n" + 
            "nb\n" + 
            "nb\n" + 
            "nb\n" + 
            "\n" + 
            "qirj\n" + 
            "jisrm\n" + 
            "jiq\n" + 
            "mjiq\n" + 
            "vhejiz\n" + 
            "\n" + 
            "zufkepilj\n" + 
            "xecokg\n" + 
            "\n" + 
            "lcpsmoruvqjyeadxkz\n" + 
            "tchgzyqjvndobxkep\n" + 
            "pwzojchxqdknevy\n" + 
            "pcxjqyzdvfeiko\n" + 
            "pnzvqwcokxyejd\n" + 
            "\n" + 
            "etpwsly\n" + 
            "xnrlpyfjc\n" + 
            "\n" + 
            "wfvprhoxyqcsk\n" + 
            "sduwyegozal\n" + 
            "bnmsaoiyzjwt\n" + 
            "\n" + 
            "sdcuajeyinfwktqhvmxblzgorp\n" + 
            "kougbfyhvetwqljzcnrmpdiasx\n" + 
            "\n" + 
            "pzmuwnoekhrfdlvgsyij\n" + 
            "ifdyvmkzpsenglowhjur\n" + 
            "sgwndvrefjimlzophkyu\n" + 
            "pgrwjmdlhvifeznksouy\n" + 
            "\n" + 
            "q\n" + 
            "q\n" + 
            "q\n" + 
            "\n" + 
            "navschjp\n" + 
            "enhavc\n" + 
            "tnvach\n" + 
            "hnavcp\n" + 
            "\n" + 
            "smxquriajlepv\n" + 
            "mqpjltuxsiva\n" + 
            "\n" + 
            "gmfzhnp\n" + 
            "mzw\n" + 
            "hmz\n" + 
            "sczmojq\n" + 
            "mpzkt\n" + 
            "\n" + 
            "lndgcav\n" + 
            "drcnalvg\n" + 
            "lncdagv\n" + 
            "gcdlvna\n" + 
            "\n" + 
            "bmhnadkozcqtfpgjwle\n" + 
            "fcztqlwmosehpik\n" + 
            "kwzbrqvhotflepcum\n" + 
            "\n" + 
            "b\n" + 
            "n\n" + 
            "\n" + 
            "haixgmlouq\n" + 
            "uxamelghiqo\n" + 
            "uohglxifndqa\n" + 
            "umhoaxgqril\n" + 
            "\n" + 
            "urhwe\n" + 
            "ngeyzami\n" + 
            "\n" + 
            "inqbavuswlkophm\n" + 
            "iwdbqfsztmrh\n" + 
            "smcwhqbi\n" + 
            "irqhbzwms\n" + 
            "\n" + 
            "tu\n" + 
            "y\n" + 
            "r\n" + 
            "mry\n" + 
            "\n" + 
            "ndpa\n" + 
            "da\n" + 
            "wda\n" + 
            "uadmk\n" + 
            "\n" + 
            "a\n" + 
            "a\n" + 
            "a\n" + 
            "a\n" + 
            "\n" + 
            "n\n" + 
            "n\n" + 
            "n\n" + 
            "\n" + 
            "h\n" + 
            "h\n" + 
            "h\n" + 
            "swk\n" + 
            "h\n" + 
            "\n" + 
            "ibdlojmetpswfqunvk\n" + 
            "iubjhxonytmadlpkqswfz\n" + 
            "icgbkljundqwtomfsp\n" + 
            "\n" + 
            "oqwjgzbv\n" + 
            "jbzeoqgwvt\n" + 
            "jlqnwgbymozuvs\n" + 
            "ovqjbgzw\n" + 
            "bvwgjoqz\n" + 
            "\n" + 
            "iosvy\n" + 
            "ituo\n" + 
            "ijoql\n" + 
            "ixolp\n" + 
            "qriko\n" + 
            "\n" + 
            "dxamz\n" + 
            "etwk\n" + 
            "ydur\n" + 
            "\n" + 
            "vlmta\n" + 
            "tmajl\n" + 
            "taml\n" + 
            "lmat\n" + 
            "\n" + 
            "flmesqdrzaphtu\n" + 
            "icbwlokjy\n" + 
            "\n" + 
            "ftjirzvc\n" + 
            "tfjzrvic\n" + 
            "jfctivrz\n" + 
            "zicrfjtv\n" + 
            "fztivcjr\n" + 
            "\n" + 
            "cqtphybfmlsre\n" + 
            "efvmbrtscpylhq\n" + 
            "bmhsyflqtecrp\n" + 
            "qscrhybfmtlep\n" + 
            "\n" + 
            "w\n" + 
            "fu\n" + 
            "ikdgacbem\n" + 
            "wfn\n" + 
            "onh\n" + 
            "\n" + 
            "lxaw\n" + 
            "xaw\n" + 
            "vxwa\n" + 
            "\n" + 
            "dor\n" + 
            "fgvru\n" + 
            "\n" + 
            "qzupn\n" + 
            "znuqp\n" + 
            "uzqpn\n" + 
            "nquzp\n" + 
            "znqup\n" + 
            "\n" + 
            "asloukc\n" + 
            "kuac\n" + 
            "uloakc\n" + 
            "kactuh\n" + 
            "rkncua\n" + 
            "\n" + 
            "pulof\n" + 
            "ofpu\n" + 
            "quopf\n" + 
            "cpuozdwkftn\n" + 
            "pjouf\n" + 
            "\n" + 
            "e\n" + 
            "e\n" + 
            "ed\n" + 
            "ce\n" + 
            "\n" + 
            "emxtn\n" + 
            "nmtex\n" + 
            "mxyent\n" + 
            "\n" + 
            "smruvqolhaxfedc\n" + 
            "amuexvdfqlrosc\n" + 
            "qdealmvxcosfru\n" + 
            "\n" + 
            "jvpnsd\n" + 
            "aethlrqbyx\n" + 
            "wszj\n" + 
            "kmvz\n" + 
            "nfck\n" + 
            "\n" + 
            "vjap\n" + 
            "vjpa\n" + 
            "japv\n" + 
            "\n" + 
            "zevwnhlk\n" + 
            "wzhvlkn\n" + 
            "zhlknwv\n" + 
            "\n" + 
            "bkge\n" + 
            "f\n" + 
            "\n" + 
            "amegkyvf\n" + 
            "nhdw\n" + 
            "phj\n" + 
            "\n" + 
            "ku\n" + 
            "uk\n" + 
            "uk\n" + 
            "uk\n" + 
            "\n" + 
            "pcszogxbatlyjrmd\n" + 
            "lgrypdxcbamoztjs\n" + 
            "tojalsmzbrdcpygx\n" + 
            "ajobgytzxsmpcrdl\n" + 
            "lbxycgdajomrztps\n" + 
            "\n" + 
            "kmnxrtelbzf\n" + 
            "iucagn\n" + 
            "\n" + 
            "xtwlso\n" + 
            "tkqlhx\n" + 
            "vxofjk\n" + 
            "utperxwf\n" + 
            "dymcnazbgx\n" + 
            "\n" + 
            "ezqcovtwshfmnuigpjb\n" + 
            "nvcqjsbfzohmewtp\n" + 
            "vqjptebrhnfomcwsz\n" + 
            "tshzvpynowcjemqfb\n" + 
            "\n" + 
            "pavisdeg\n" + 
            "uhmraivpnd\n" + 
            "gdeyicpqva\n" + 
            "\n" + 
            "wgutqadflbvkypmen\n" + 
            "ftxjaroshlmyknvbgc\n" + 
            "\n" + 
            "ymnlca\n" + 
            "ld\n" + 
            "\n" + 
            "wkxmutlnpocyfsi\n" + 
            "lcfywkbomxuqpits\n" + 
            "uikmxocwsfpylt\n" + 
            "luyctosfwxkmpi\n" + 
            "\n" + 
            "tmiaozewnsxcdpuj\n" + 
            "zryoegivjw\n" + 
            "wqheorjzi\n" + 
            "iwboflkejzg\n" + 
            "\n" + 
            "cszpdujkih\n" + 
            "volmrxbayfngwt\n" + 
            "\n" + 
            "safhirtdbjkcegvwxl\n" + 
            "xrbdztjhpuifswon\n" + 
            "\n" + 
            "x\n" + 
            "o\n" + 
            "o\n" + 
            "o\n" + 
            "\n" + 
            "d\n" + 
            "d\n" + 
            "d\n" + 
            "zd\n" + 
            "\n" + 
            "ofiv\n" + 
            "htrzonqfs\n" + 
            "mfeoc\n" + 
            "fo\n" + 
            "odfx\n" + 
            "\n" + 
            "zjrgniftodpxkeyclasvqm\n" + 
            "ogquzlrnkbscamfvxdipety\n" + 
            "arpixfvntdlkzoyghmqecjs\n" + 
            "\n" + 
            "qu\n" + 
            "uq\n" + 
            "qu\n" + 
            "qdihywug\n" + 
            "\n" + 
            "eazntkqdubsi\n" + 
            "usiqgkzrtbno\n" + 
            "bztisndyqruk\n" + 
            "tiebnsjqzcku\n" + 
            "usihtqkmpbnz\n" + 
            "\n" + 
            "neqhxtfvudrizywalg\n" + 
            "zgtfwhuivxckrjayenql\n" + 
            "zurpeiwlvhbsxqgnafmty\n" + 
            "yhwtgqvflknziaexru\n" + 
            "tghwvqknlcrixaefuozy\n" + 
            "\n" + 
            "cuoigxtdj\n" + 
            "gdjuocixt\n" + 
            "itucgjoxd\n" + 
            "utdocxgij\n" + 
            "xodgjucit\n" + 
            "\n" + 
            "cgod\n" + 
            "dgqo\n" + 
            "dlgo\n" + 
            "dgo\n" + 
            "\n" + 
            "voqcynwa\n" + 
            "kzwdqofeyux\n" + 
            "qwoy\n" + 
            "ylowqa\n" + 
            "qwyoa\n" + 
            "\n" + 
            "ti\n" + 
            "bptxr\n" + 
            "ypti\n" + 
            "keatmfg\n" + 
            "tcu\n" + 
            "\n" + 
            "cvzqoytnxgidkh\n" + 
            "ogqikczyndax\n" + 
            "bczqgnjxykodim\n" + 
            "qoiycgdzxfhkn\n" + 
            "ckexgiozndhuqyf\n" + 
            "\n" + 
            "jptmev\n" + 
            "akgqlf\n" + 
            "\n" + 
            "lmkhwuiq\n" + 
            "qhwfuimk\n" + 
            "khlmuiq\n" + 
            "vnskicqpmhu\n" + 
            "ikhmqu\n" + 
            "\n" + 
            "xguq\n" + 
            "qxau\n" + 
            "thdscqfujxo\n" + 
            "unqvyzx\n" + 
            "\n" + 
            "wyoxgtdcabm\n" + 
            "kujznr\n" + 
            "\n" + 
            "z\n" + 
            "ghw\n" + 
            "od\n" + 
            "ruz\n" + 
            "ur\n" + 
            "\n" + 
            "wdyrgszfk\n" + 
            "dkswzpmcg\n" + 
            "qijudskwgzvba\n" + 
            "psdcrwgtknz\n" + 
            "\n" + 
            "u\n" + 
            "f\n" + 
            "\n" + 
            "reboadyv\n" + 
            "movdetp\n" + 
            "dveo\n" + 
            "\n" + 
            "pg\n" + 
            "pdz\n" + 
            "\n" + 
            "gnybh\n" + 
            "yghbns\n" + 
            "bhgyn\n" + 
            "\n" + 
            "ypwthadrxqvfnjsbgek\n" + 
            "wijrnspagfvbeckxydqh\n" + 
            "rhwafjngdvypqeskbx\n" + 
            "vhjnwoepxkfrdbgsyqa\n" + 
            "qwrsgekhjnpyfvbdxa\n" + 
            "\n" + 
            "ztqscidfjomhykl\n" + 
            "zwteyqhvbrxcusnp\n" + 
            "\n" + 
            "y\n" + 
            "gy\n" + 
            "lfyi\n" + 
            "\n" + 
            "fbv\n" + 
            "e\n" + 
            "\n" + 
            "xq\n" + 
            "mquh\n" + 
            "qu\n" + 
            "\n" + 
            "g\n" + 
            "g\n" + 
            "g\n" + 
            "gma\n" + 
            "g\n" + 
            "\n" + 
            "xnrhqugisdbakwo\n" + 
            "kjlaixgorsupmncwbqhd\n" + 
            "\n" + 
            "udewvom\n" + 
            "omdvgfe\n" + 
            "zbveomrxd\n" + 
            "demov\n" + 
            "mvdouge\n" + 
            "\n" + 
            "qjoblvgheczrwtx\n" + 
            "swraevbthxgfozljk\n" + 
            "estomhrjgdbylvwxuaz\n" + 
            "luvewtpxyjgorznbhm\n" + 
            "\n" + 
            "pynkdbuojrgxwaf\n" + 
            "vbcxitrkdlasefhm\n" + 
            "jfgxkdwbqazry\n" + 
            "\n" + 
            "lbsjwteodqmri\n" + 
            "bikqgdmsalnjoetr\n" + 
            "dqtispjobreml\n" + 
            "jdsortielqmvby\n" + 
            "wremliobqtyhsdj\n" + 
            "\n" + 
            "adnbw\n" + 
            "yedl\n" + 
            "dw\n" + 
            "xzsodcjiptru\n" + 
            "\n" + 
            "ycpmubrlnakv\n" + 
            "pngelumybhzrvca\n" + 
            "vcunolrfapbym\n" + 
            "lmpcvbnouatry\n" + 
            "yprljcmwnaubv\n" + 
            "\n" + 
            "tfs\n" + 
            "fzusw\n" + 
            "sf\n" + 
            "qfs\n" + 
            "\n" + 
            "tvfe\n" + 
            "meifo\n" + 
            "\n" + 
            "sldgu\n" + 
            "dp\n" + 
            "hd\n" + 
            "wd\n" + 
            "dw\n" + 
            "\n" + 
            "hnsp\n" + 
            "ghpdn\n" + 
            "\n" + 
            "zpqjuskxmh\n" + 
            "pjfnvrbwzlkeaqi\n" + 
            "\n" + 
            "g\n" + 
            "wg\n" + 
            "g\n" + 
            "g\n" + 
            "\n" + 
            "jvmqoah\n" + 
            "ujavhoxqkm\n" + 
            "qhmovaj\n" + 
            "\n" + 
            "btmfvhxdwonsylk\n" + 
            "ftloywdvhxnsqkziba\n" + 
            "hktxvnfodwylsb\n" + 
            "nkfvoltxysdbwh\n" + 
            "ofwyvthbnkslxd\n" + 
            "\n" + 
            "m\n" + 
            "pm\n" + 
            "m\n" + 
            "\n" + 
            "cjmyvtelzpnfrwiduxg\n" + 
            "iyldcfmvuxtzngrpwej\n" + 
            "edcigutzrfnymwvlxpj\n" + 
            "zurcijpvtxmwnlfgdey\n" + 
            "wtphfcneuxzmygirlvdaj\n" + 
            "\n" + 
            "r\n" + 
            "hr\n" + 
            "\n" + 
            "fnrvmyipeqoxs\n" + 
            "ordialpfsnukgq\n" + 
            "\n" + 
            "w\n" + 
            "ew\n" + 
            "fbqalwz\n" + 
            "wxotv\n" + 
            "vw\n" + 
            "\n" + 
            "dqvge\n" + 
            "qise\n" + 
            "\n" + 
            "gsw\n" + 
            "swg\n" + 
            "bywagsd\n" + 
            "\n" + 
            "rxckvmn\n" + 
            "hcgjvslm\n" + 
            "mvxct\n" + 
            "wefnbkcmv\n" + 
            "mvxcu\n" + 
            "\n" + 
            "xcwzey\n" + 
            "xtyzwnc\n" + 
            "fzaxcwyvq\n" + 
            "zctyxw\n" + 
            "\n" + 
            "jnocisgywbmf\n" + 
            "onfiyscjhmb\n" + 
            "yprobjsncmfiake\n" + 
            "nmosbjxcyif\n" + 
            "\n" + 
            "xphuvayzcgoim\n" + 
            "yxauhcgiozp\n" + 
            "\n" + 
            "zftwuynbiel\n" + 
            "rjdscqm\n" + 
            "rkgvpa\n" + 
            "xpcd\n" + 
            "\n" + 
            "wjekdnzcgvoxhrqaf\n" + 
            "rkteqznvdiwcfhau\n" + 
            "\n" + 
            "oeqbtdughnky\n" + 
            "kgtfbyhqvonz\n" + 
            "hovgyqnktb\n" + 
            "gynzqhtkob\n" + 
            "kbyhaotnqg\n" + 
            "\n" + 
            "ryijtk\n" + 
            "eykbgcurd\n" + 
            "nwhalmrqzs\n" + 
            "ftxiprb\n" + 
            "\n" + 
            "nvukwexhl\n" + 
            "vhewxpklu\n" + 
            "hkldweuv\n" + 
            "\n" + 
            "bmaiofgpdrvshtulenx\n" + 
            "itxevfuaodrpslmhgbqn\n" + 
            "obsxpmdiuhfatrgenvl\n" + 
            "phxivmfdbslonrtegazwu\n" + 
            "hngfsquprxtlbvmidoae\n" + 
            "\n" + 
            "xsdlipbamr\n" + 
            "sbipdrlmx\n" + 
            "pxmsbiwrdl\n" + 
            "pmixqlrsndzcb\n" + 
            "\n" + 
            "wtcbnjfuxhzig\n" + 
            "dftoqsezpynmr\n" + 
            "\n" + 
            "bhr\n" + 
            "jdqhnkbo\n" + 
            "\n" + 
            "wmfuhtpsac\n" + 
            "swymjpaucthf\n" + 
            "\n" + 
            "w\n" + 
            "wk\n" + 
            "w\n" + 
            "w\n" + 
            "w\n" + 
            "\n" + 
            "mntdkfcpbhgxu\n" + 
            "htfkcundmbxgp\n" + 
            "ngdypxutkmfhwbc\n" + 
            "bskmthngcduxfp\n" + 
            "\n" + 
            "bhijdqfwvrtazumsokgxnyplc\n" + 
            "rbeimqjdynwacfstkozxlhpg\n" + 
            "\n" + 
            "czoalyjudsvpwe\n" + 
            "fkdlpsjwyeagz\n" + 
            "\n" + 
            "jkwilvay\n" + 
            "vliktwjay\n" + 
            "lncfjawkiyq\n" + 
            "liykwaj\n" + 
            "\n" + 
            "nt\n" + 
            "qzvliprt\n" + 
            "tb\n" + 
            "aut\n" + 
            "\n" + 
            "wqzpuodtkmcejhxaf\n" + 
            "awdchemztxkoupjqf\n" + 
            "pcoemuqjwdhfatxkz\n" + 
            "ofjexaptcquhmwdzk\n" + 
            "\n" + 
            "lh\n" + 
            "lh\n" + 
            "lhy\n" + 
            "\n" + 
            "fkdpxacim\n" + 
            "anhxqel\n" + 
            "\n" + 
            "mowadzr\n" + 
            "dzwrma\n" + 
            "dzwrma\n" + 
            "dazrmw\n" + 
            "wazmrd\n" + 
            "\n" + 
            "w\n" + 
            "w\n" + 
            "w\n" + 
            "sw\n" + 
            "\n" + 
            "yvqgztocs\n" + 
            "jfeoxwi\n" + 
            "anrdqom\n" + 
            "\n" + 
            "dck\n" + 
            "jghkn\n" + 
            "\n" + 
            "mb\n" + 
            "mqeb\n" + 
            "jc\n" + 
            "vq\n" + 
            "\n" + 
            "bcxkdsl\n" + 
            "ksbcxfld\n" + 
            "kclxsbd\n" + 
            "dcklbsx\n" + 
            "xdzsklcb\n" + 
            "\n" + 
            "wblktjrmc\n" + 
            "tpbflrkcjm\n" + 
            "\n" + 
            "ydibtqk\n" + 
            "odtkiby\n" + 
            "bndtk\n" + 
            "bdkyqt\n" + 
            "mtzwvxdkb\n" + 
            "\n" + 
            "extbpglsow\n" + 
            "rytfgvbwxe\n" + 
            "gmzxdiatjuwqbkn\n" + 
            "obcspgfhewtx\n" + 
            "\n" + 
            "cimkxgjpyel\n" + 
            "yjilemkgcxp\n" + 
            "\n" + 
            "mpkihj\n" + 
            "hmipjk\n" + 
            "khpmij\n" + 
            "hpkmij\n" + 
            "\n" + 
            "tkmcyp\n" + 
            "ktycpm\n" + 
            "kmpytc\n" + 
            "\n" + 
            "v\n" + 
            "v\n" + 
            "kbv\n" + 
            "hvn\n" + 
            "\n" + 
            "gmipxsrwzbjoqekfhyldnuva\n" + 
            "gxukpmybrawshflzvioeqjd\n" + 
            "jbdhvqwoylxpgrfszekmuica\n" + 
            "jgsopaeiqldfrvhbmxwuzyk\n" + 
            "\n" + 
            "xgwrvakysu\n" + 
            "gyxrvskwau\n" + 
            "\n" + 
            "admkgrynsc\n" + 
            "ycaknjdrsfbg\n" + 
            "\n" + 
            "nukcsbqv\n" + 
            "vqcbsukn\n" + 
            "cnsvubkq\n" + 
            "\n" + 
            "xldicfuo\n" + 
            "dugplxiyvqrmo\n" + 
            "\n" + 
            "vo\n" + 
            "hov\n" + 
            "\n" + 
            "swmptlvkaibqynhrfj\n" + 
            "vfkwthibjpnaymqlsr\n" + 
            "\n" + 
            "fg\n" + 
            "fgj\n" + 
            "gf\n" + 
            "fg\n" + 
            "\n" + 
            "fail\n" + 
            "hlaiv\n" + 
            "icfalh\n" + 
            "adlji\n" + 
            "aliv\n" + 
            "\n" + 
            "xafmqoucv\n" + 
            "yzwsc\n" + 
            "\n" + 
            "uacomdegxsrikq\n" + 
            "ficekhgasxtqb\n" + 
            "\n" + 
            "hwi\n" + 
            "y\n" + 
            "p\n" + 
            "p\n" + 
            "r\n" + 
            "\n" + 
            "lgdfhsec\n" + 
            "gehzl\n" + 
            "lhgek\n" + 
            "\n" + 
            "tqsbofgmpiuhzvnywcxrde\n" + 
            "egqdaynruxjvishzbmkwcpotf\n" + 
            "\n" + 
            "odl\n" + 
            "dlo\n" + 
            "dol\n" + 
            "old\n" + 
            "\n" + 
            "jyp\n" + 
            "yjp\n" + 
            "pyj\n" + 
            "jpy\n" + 
            "\n" + 
            "m\n" + 
            "m\n" + 
            "m\n" + 
            "m\n" + 
            "jm\n" + 
            "\n" + 
            "omu\n" + 
            "wbagmxl\n" + 
            "\n" + 
            "ibswalzhptjxgqre\n" + 
            "pehtxzqbsglirjaw\n" + 
            "bjewlsrxaqitzpgh\n" + 
            "\n" + 
            "lesxvkyjzmhgobcinpqfatu\n" + 
            "rvyoisltudagqbpmcxnkh\n" + 
            "\n" + 
            "fq\n" + 
            "nf\n" + 
            "ufq\n" + 
            "\n" + 
            "codalnsiyxmbphvkezug\n" + 
            "dkxvtbyehosacimplugzn\n" + 
            "icudxomwpzsbavfnklhegy\n" + 
            "imxsqlahogdnbkcevupzy\n" + 
            "\n" + 
            "ukdosqyfztcpjblnvw\n" + 
            "cwbndosytvzfljupq\n" + 
            "dnfjzscwpqobtlyvu\n" + 
            "wrngvcpjqbsxuytzodfle\n" + 
            "uvdcjtwopnsfbalqzy\n" + 
            "\n" + 
            "gzynvqbmusairxfceodjhptk\n" + 
            "dzhvnpbwuqitsegrfk\n" + 
            "\n" + 
            "s\n" + 
            "s\n" + 
            "s\n" + 
            "s\n" + 
            "\n" + 
            "xtchdjm\n" + 
            "tmwjdhrxc\n" + 
            "jdxhcvtfb\n" + 
            "zhxyjtdleuc\n" + 
            "pcqtxdhgijn\n" + 
            "\n" + 
            "qdnjwxrkco\n" + 
            "crkwxjqodn\n" + 
            "\n" + 
            "wgsrjitlu\n" + 
            "iwrsuljt\n" + 
            "jcwrfstuil\n" + 
            "\n" + 
            "ke\n" + 
            "dbiek\n" + 
            "\n" + 
            "cswhaxt\n" + 
            "xatcsb\n" + 
            "ynaxoz\n" + 
            "\n" + 
            "tfh\n" + 
            "oi\n" + 
            "x\n" + 
            "bxk\n" + 
            "\n" + 
            "irebuqzmyodjv\n" + 
            "bdmzvcaefyip\n" + 
            "ebmihatfnvzwyd\n" + 
            "bistwmyzvekd\n" + 
            "\n" + 
            "iz\n" + 
            "yinwqg\n" + 
            "i\n" + 
            "ic\n" + 
            "bci\n" + 
            "\n" + 
            "cosrikjymatwvfqlz\n" + 
            "csxluqmkyfdwzjirpeonbh\n" + 
            "\n" + 
            "omjhzgublxirenyq\n" + 
            "snyojluiczmqabx\n" + 
            "\n" + 
            "n\n" + 
            "wri\n" + 
            "l\n" + 
            "h\n" + 
            "\n" + 
            "ywgtbzjeaslqm\n" + 
            "mxfpskavncuhdgojw\n" + 
            "\n" + 
            "khrbzjwgdc\n" + 
            "cjkdsfrwzhg\n" + 
            "xzkajhvpcgedrw\n" + 
            "gkjwhzrcqdb\n" + 
            "\n" + 
            "uoalpmie\n" + 
            "mwpetola\n" + 
            "szbgxapenvlmo\n" + 
            "oeumjlpha\n" + 
            "etplwmaio\n" + 
            "\n" + 
            "xpvroeaisngmlhbfqw\n" + 
            "bosflmwxhevdrapinqg\n" + 
            "nerlixfbmvgaqwohpts\n" + 
            "\n" + 
            "m\n" + 
            "m\n" + 
            "m\n" + 
            "ml\n" + 
            "m\n" + 
            "\n" + 
            "epifnq\n" + 
            "vfg\n" + 
            "vtqyp\n" + 
            "rwmsohla\n" + 
            "\n" + 
            "banpsul\n" + 
            "sbunpla\n" + 
            "bnupasl\n" + 
            "\n" + 
            "nayjbuo\n" + 
            "vyb\n" + 
            "zkwbht\n" + 
            "qba\n" + 
            "fsb\n" + 
            "\n" + 
            "saigt\n" + 
            "siatg\n" + 
            "iagst\n" + 
            "\n" + 
            "kxzaqpfbr\n" + 
            "fazqxprbk\n" + 
            "rfbpakzxq\n" + 
            "rbzxqapkf\n" + 
            "\n" + 
            "tvj\n" + 
            "vjt\n" + 
            "jivt\n" + 
            "\n" + 
            "ulmzskv\n" + 
            "szmavu\n" + 
            "svmkzu\n" + 
            "mszukqiv\n" + 
            "uslmhzv\n" + 
            "\n" + 
            "ezcfdlhbutxgqn\n" + 
            "gonakuefqtdzchbx\n" + 
            "sfugdecnxhbktqz\n" + 
            "xghtbdzqfencu\n" + 
            "nmgvethpfudqxczb\n" + 
            "\n" + 
            "xnhcmilzvd\n" + 
            "wvghcdxmnl\n" + 
            "\n" + 
            "lgopqtnhjxeaykmwbuc\n" + 
            "gknjxptbhluocqmwey\n" + 
            "ibjdwczrugmqkpfntsove\n" + 
            "\n" + 
            "hbzkyupxvdjceqnalmtwi\n" + 
            "jmtxqdyhwpkiurencbgs\n" + 
            "\n" + 
            "xh\n" + 
            "xh\n" + 
            "hmx\n" + 
            "\n" + 
            "oujkpir\n" + 
            "cujpordi\n" + 
            "ohiujrtwqm\n" + 
            "ijrlou\n" + 
            "oxrdjui\n" + 
            "\n" + 
            "cvxswn\n" + 
            "csvxnw\n" + 
            "\n" + 
            "zvn\n" + 
            "enzv\n" + 
            "nvz\n" + 
            "\n" + 
            "oldxznphmsfevack\n" + 
            "vianfgqeolmxcdkprszh\n" + 
            "dzklxvmaehnfpcso\n" + 
            "fsvmupcojznaehxkdl\n" + 
            "slzjfhdpxmaeonvkc\n" + 
            "\n" + 
            "fuzhqtvmcykspworxd\n" + 
            "gicoeyhfulvbtkpwsxqzm\n" + 
            "fzxwpvkmcjuqshyto\n" + 
            "pcwzuqmkvxhotyfjsr\n" + 
            "\n" + 
            "inemvpxyzkgawbslfuhqtj\n" + 
            "xvtzelbnfasupqwjimghky\n" + 
            "\n" + 
            "bax\n" + 
            "xba\n" + 
            "bxa\n" + 
            "\n" + 
            "ycnpvlkxrsqteuzabhig\n" + 
            "trokmebpcqvxslgyajid\n" + 
            "esqbalgcvkpyxifrwt\n" + 
            "lvtergkacpsixqbym\n" + 
            "keqxrvatldcpsybigfw\n" + 
            "\n" + 
            "gqyh\n" + 
            "oygh\n" + 
            "zdgphesv\n" + 
            "\n" + 
            "gsnlyfvdietjzhr\n" + 
            "tnvjshzygelrid\n" + 
            "slzgoyinjvhedtbr\n" + 
            "\n" + 
            "dmkho\n" + 
            "dokmh\n" + 
            "hkmod\n" + 
            "dmokh\n" + 
            "kmohd\n" + 
            "\n" + 
            "tj\n" + 
            "adtw\n" + 
            "tj\n" + 
            "\n" + 
            "eotbyclkrguzvfqhwsnapidx\n" + 
            "tiwvdxzhoapebrukcqfnysg\n" + 
            "qjcwohutrkxdefasipyzbngmv\n" + 
            "\n" + 
            "uiecjkqtdfgahzsnlmrv\n" + 
            "htjfkvlyqeiznacdmsgu\n" + 
            "gzfvdqsmalnueokyihtcj\n" + 
            "gzfsenjukcwmatipvqdlhx\n" + 
            "lhvzntecrigmqfjuaysdk\n" + 
            "\n" + 
            "deun\n" + 
            "vkwchol\n" + 
            "\n" + 
            "yfdpogbcha\n" + 
            "cgbpdfonah\n" + 
            "zocugfvpkqadhb\n" + 
            "hpoyfgabdc\n" + 
            "phbdomgcaf\n" + 
            "\n" + 
            "keazbgtc\n" + 
            "ycwhrxtj\n" + 
            "\n" + 
            "tsiprzbdgxeuhq\n" + 
            "uxtesbpizgrqhdk\n" + 
            "hsxtpribzdgeuqo\n" + 
            "nslztrupibedxqmhg\n" + 
            "txhudzperbiqgs\n" + 
            "\n" + 
            "drvmikacytsxwbeghzqpnflo\n" + 
            "frsbqzyhkvacuwidemlntpgo\n" + 
            "wprfmeklvdzocitaghyqnsb\n" + 
            "mgtsdiaewvbhzyclnrkqpof\n" + 
            "gvbhntlokipzwcsafydqemr\n" + 
            "\n" + 
            "pigblohae\n" + 
            "lgiaobefph\n" + 
            "bgeoahpli\n" + 
            "\n" + 
            "sfjecuzdnhikbla\n" + 
            "adizbhsucefnlk\n" + 
            "askzenidlyfubch\n" + 
            "\n" + 
            "xnscfiwq\n" + 
            "\n" + 
            "gwcaisqmko\n" + 
            "cquelfwskoam\n" + 
            "dwvnkamcoq\n" + 
            "lfiakwgcmuoebq\n" + 
            "\n" + 
            "repbn\n" + 
            "xnlrkbe\n" + 
            "\n" + 
            "lwpsfim\n" + 
            "smfip\n" + 
            "mfpis\n" + 
            "mitsfp\n" + 
            "msijzpbfyqhd\n" + 
            "\n" + 
            "tcdasxurvbpil\n" + 
            "fsiogjpwuvryxc\n" + 
            "\n" + 
            "jviehcgmkzsrb\n" + 
            "ihkmgcsjebrz\n" + 
            "bmrhjeczgski\n" + 
            "bimgkjcezhsr\n" + 
            "mlgcsedbzjkhrpi\n" + 
            "\n" + 
            "jokl\n" + 
            "azuj\n" + 
            "\n" + 
            "lxqsdcmhiz\n" + 
            "uqyidhcxsm\n" + 
            "mdisyxcqh\n" + 
            "sqcxdhimu\n" + 
            "qdhicgxms\n" + 
            "\n" + 
            "eamzlpf\n" + 
            "hamze\n" + 
            "seryna\n" + 
            "gapel\n" + 
            "\n" + 
            "mlzqupv\n" + 
            "qauzmp\n" + 
            "qwmrycgzufk\n" + 
            "mxqpzu\n" + 
            "\n" + 
            "txesa\n" + 
            "tjnsxha\n" + 
            "\n" + 
            "alejmqrzdkfu\n" + 
            "hoikwybxgct\n" + 
            "\n" + 
            "bfz\n" + 
            "fzb\n" + 
            "fzb\n" + 
            "zfb\n" + 
            "\n" + 
            "ts\n" + 
            "tfs\n" + 
            "tsb\n" + 
            "bs\n" + 
            "qsm\n" + 
            "\n" + 
            "oyavgjdq\n" + 
            "yqavriodgj\n" + 
            "qjyokgadv\n" + 
            "yvacgqojd\n" + 
            "jovdagbqy\n" + 
            "\n" + 
            "dnr\n" + 
            "mnkpd\n" + 
            "negtdic\n" + 
            "\n" + 
            "tqo\n" + 
            "toq\n" + 
            "\n" + 
            "tjdfnbw\n" + 
            "ndbrwtijf\n" + 
            "wjemfndtg\n" + 
            "ndfwjt\n" + 
            "\n" + 
            "cbyerjfswukahqztlgxiv\n" + 
            "saqgctvujielndbfhyxrwk\n" + 
            "ecvksyafthpwqxrligumbjo\n" + 
            "\n" + 
            "qbcjoewshurtfg\n" + 
            "jetpcgsohwur\n" + 
            "igsrcubjqtehwo\n" + 
            "iehwgvujcxokrstq\n" + 
            "coasdruheltyzgjwm\n" + 
            "\n" + 
            "ct\n" + 
            "rjcqz\n" + 
            "\n" + 
            "bzoelsru\n" + 
            "uetcbslzr\n" + 
            "otlzubew\n" + 
            "elxznuj\n" + 
            "\n" + 
            "mywgbvir\n" + 
            "ruyzcmbw\n" + 
            "\n" + 
            "lit\n" + 
            "ctrbedu\n" + 
            "pty\n" + 
            "\n" + 
            "jcyaxzlmvfq\n" + 
            "vfqycxiazl\n" + 
            "nmxlqzavcfy\n" + 
            "lxynrvqzcfa\n" + 
            "\n" + 
            "d\n" + 
            "bd\n" + 
            "\n" + 
            "vxphwrltze\n" + 
            "hadrexjwouz\n" + 
            "\n" + 
            "cukwtrvlimzboqjndpfaxe\n" + 
            "euljtvdbmoiparzfnqwxck\n" + 
            "aqzcukrwetdbvmijnxplfo\n" + 
            "aduqijzxotmbwkcpfnverl\n" + 
            "ramfvtnqluwecjbzkxpiod\n" + 
            "\n" + 
            "ztogrd\n" + 
            "todzbf\n" + 
            "otdz\n" + 
            "\n" + 
            "wqkpirxs\n" + 
            "rgmkpiefsuyz\n" + 
            "psiovqkr\n" + 
            "\n" + 
            "boedrhycwgui\n" + 
            "cjryhdbowzu\n" + 
            "douywhrbc\n" + 
            "\n" + 
            "aibqxmktodwlvgr\n" + 
            "lgmdoxjsiakryqwv\n" + 
            "voirwaglnxqdkm\n" + 
            "rwtbmdqvkalxogi\n" + 
            "\n" + 
            "lnhpb\n" + 
            "ixmcgjy\n" + 
            "\n" + 
            "myrjecvnfz\n" + 
            "gosuwaxkinlh\n" + 
            "\n" + 
            "jkesf\n" + 
            "ftdk\n" + 
            "vfgciokl\n" + 
            "fk\n" + 
            "dfrk\n" + 
            "\n" + 
            "atyxewdc\n" + 
            "dwxtyeca\n" + 
            "ctyawdxe\n" + 
            "xyatwdec\n" + 
            "tycedxaw\n" + 
            "\n" + 
            "jcwf\n" + 
            "jfbq\n" + 
            "\n" + 
            "lxrk\n" + 
            "xkrl\n" + 
            "rkxlw\n" + 
            "rlxk\n" + 
            "lkxr\n" + 
            "\n" + 
            "gpxcbvaftykhmlndz\n" + 
            "bagltzchksixvm\n" + 
            "\n" + 
            "xfynzbavgcluikseqprojdhmwt\n" + 
            "fnxlkuapzsmivgwcbrdeohjqt\n" + 
            "qgsvxmhjdfwanuozbtpiklrec\n" + 
            "\n" + 
            "pwbgiyrmoncveh\n" + 
            "ijrnkyxchbw\n" + 
            "\n" + 
            "kdzjqfwuemtrx\n" + 
            "kdrwzemxpfqtju\n" + 
            "mtxrdjuzwflqek\n" + 
            "\n" + 
            "nm\n" + 
            "cgm\n" + 
            "mxe\n" + 
            "mt\n" + 
            "mkg\n" + 
            "\n" + 
            "xhvfa\n" + 
            "elbrtnkf\n" + 
            "myrqcfe\n" + 
            "wfpd\n" + 
            "\n" + 
            "xtacwlbzqyep\n" + 
            "gwtfyevzr\n" + 
            "uezjhwiryt\n" + 
            "towyezn\n" + 
            "hwytzekdf\n" + 
            "\n" + 
            "pstabwxjrdzfnhmy\n" + 
            "zbhtxaswpcmdjvfrn\n" + 
            "hnldprtxabzwfjsm\n" + 
            "\n" + 
            "hmnqt\n" + 
            "ehy\n" + 
            "hy\n" + 
            "\n" + 
            "ejnrgfsptmqhw\n" + 
            "ry\n" + 
            "rauocv\n" + 
            "xrz\n" + 
            "rboluyxc\n" + 
            "\n" + 
            "ltosmwxgbnrkyvhipf\n" + 
            "ewupcknqlzhxbdosmf\n" + 
            "\n" + 
            "dschnrkmg\n" + 
            "bspywutlz\n" + 
            "\n" + 
            "pnbealkorcyimwxtszq\n" + 
            "qcpyirxotlkmnbe\n" + 
            "inyxkqrtmobcepl\n" + 
            "jykctmiroqxnbpel\n" + 
            "\n" + 
            "xsneqikjr\n" + 
            "juxoq\n" + 
            "\n" + 
            "yvtmr\n" + 
            "mryvt\n" + 
            "tvrmy\n" + 
            "\n" + 
            "jrnoewdasxtpykfuhbivlczqm\n" + 
            "djzmscybhklwqvfxpuoraenit\n" + 
            "\n" + 
            "ijpkdhasnbzof\n" + 
            "vkyglectu\n" + 
            "kgqmter\n" + 
            "\n" + 
            "aevqjpgldrimhyzt\n" + 
            "jvpzyiqgmeadrtlxh\n" + 
            "tagsqhdreymzpiljv\n" + 
            "javdypqmletzirgh\n" + 
            "tvhgdymiapjqrelz\n" + 
            "\n" + 
            "pltehmo\n" + 
            "hteo\n" + 
            "kthucwjzen\n" + 
            "\n" + 
            "sdbpk\n" + 
            "dpsbk\n" + 
            "pkbds\n" + 
            "dpskbw\n" + 
            "\n" + 
            "vhg\n" + 
            "kveypo\n" + 
            "gkyhvb\n" + 
            "vy\n" + 
            "umvanlfjtxiz\n" + 
            "\n" + 
            "rnwpedjyxfa\n" + 
            "xnpwdjaryfe\n" + 
            "naclpdxyjwref\n" + 
            "wirnxspyfkedjaq\n" + 
            "axfdepwjrny\n" + 
            "\n" + 
            "lsvmnhowcaqibz\n" + 
            "qmzlwdnhoravscib\n" + 
            "bvazqcyhilsmnwo\n" + 
            "aqnzslbvmyichow\n" + 
            "\n" + 
            "fld\n" + 
            "lf\n" + 
            "\n" + 
            "wsqgeuvhkao\n" + 
            "ovawskghequ\n" + 
            "howguavsqke\n" + 
            "vkqghseawou\n" + 
            "asvguwophqek\n" + 
            "\n" + 
            "fyimlhcanpogxbedsktjv\n" + 
            "alhbsctvpjinofkgxd\n" + 
            "\n" + 
            "xzweq\n" + 
            "wzexqu\n" + 
            "zwxerq\n" + 
            "zeqwx\n" + 
            "\n" + 
            "pvtnwuxdblgi\n" + 
            "lxdkihc\n" + 
            "lxeid\n" + 
            "xlidqa\n" + 
            "\n" + 
            "endkrg\n" + 
            "giepnvqamk\n" + 
            "cgnfek\n" + 
            "gkne\n" + 
            "xlrnkgeb\n" + 
            "\n" + 
            "jocivswhm\n" + 
            "uhwspmgedifzvtc\n" + 
            "xwohivjerysg\n" + 
            "vqlwasink\n" + 
            "\n" + 
            "cnqwfozbyp\n" + 
            "gomhzqlyuxpjntsbf\n" + 
            "inbvcofqypz\n" + 
            "\n" + 
            "jkcoleqvgnmfhubdi\n" + 
            "vfgjmrdubkihon\n" + 
            "uvfkdzhjogbimn\n" + 
            "hyuvgbpironfkdjm\n" + 
            "\n" + 
            "yidtrshqu\n" + 
            "xb\n" + 
            "nowk\n" + 
            "\n" + 
            "utmgyzvxkdirepasboq\n" + 
            "fqrveltcmngwkusxdyj\n" + 
            "\n" + 
            "yfe\n" + 
            "efy\n" + 
            "fey\n" + 
            "\n" + 
            "alfrkixuqtpjmn\n" + 
            "wghmcpozdavbln\n" + 
            "\n" + 
            "yoac\n" + 
            "yoca\n" + 
            "cyao\n" + 
            "coay\n" + 
            "cdyoa\n" + 
            "\n" + 
            "rqemgnsbac\n" + 
            "nerzsubthqcvopa\n" + 
            "sqencbra\n" + 
            "aicfmnbesrq\n" + 
            "\n" + 
            "apdhe\n" + 
            "phdae\n" + 
            "phead\n" + 
            "\n" + 
            "donrvtgfpawjczil\n" + 
            "smkubqe\n" + 
            "hsxy\n" + 
            "\n" + 
            "gzndv\n" + 
            "gvnfzd\n" + 
            "nzvrgd\n" + 
            "vgrdnz\n" + 
            "nxiugzdvk\n" + 
            "\n" + 
            "pdy\n" + 
            "syp\n" + 
            "py\n" + 
            "\n" + 
            "pmgwdu\n" + 
            "ufdpwgm\n" + 
            "amdwpghu\n" + 
            "mdlwgypu\n" + 
            "aupdwgmxc\n" + 
            "\n" + 
            "trgiw\n" + 
            "sbtgxp\n" + 
            "kzagomtjeruh\n" + 
            "tyfzog\n" + 
            "\n" + 
            "i\n" + 
            "i\n" + 
            "g\n" + 
            "\n" + 
            "dwugnpkixrcsb\n" + 
            "rzgakpliw\n" + 
            "iprkwga\n" + 
            "wajpirkg\n" + 
            "igwjzhpkr\n" + 
            "\n" + 
            "sbm\n" + 
            "pmbgs\n" + 
            "bxmqvt\n" + 
            "\n" + 
            "sxrwktpbfcezjgnuhiv\n" + 
            "rezgdublajypixvq\n" + 
            "\n" + 
            "lcxekub\n" + 
            "uxeabclk\n" + 
            "xceufkbl\n" + 
            "ecbulxk\n" + 
            "\n" + 
            "tgbnl\n" + 
            "btlgn\n" + 
            "blgnt\n" + 
            "gtbln\n" + 
            "\n" + 
            "xcyasnqmb\n" + 
            "yukatveidfrjhgpo\n" + 
            "wzya\n" + 
            "wylam\n" + 
            "\n" + 
            "gx\n" + 
            "xg\n" + 
            "\n" + 
            "swuincbqj\n" + 
            "qijcnuwb\n" + 
            "cijqwbnu\n" + 
            "wncbjqiu\n" + 
            "\n" + 
            "qv\n" + 
            "qv\n" + 
            "vq\n" + 
            "\n" + 
            "baqn\n" + 
            "uqban\n" + 
            "aeqbn\n" + 
            "xypaqnb\n" + 
            "nabq\n" + 
            "\n" + 
            "nbiklgszxqfv\n" + 
            "znlvibsfqkxg\n" + 
            "xfvnqzlkibgs\n" + 
            "\n" + 
            "cruevqwxagzhkn\n" + 
            "jfyixpousmnldrbtz\n" + 
            "\n" + 
            "om\n" + 
            "om\n" + 
            "om\n" + 
            "nom\n" + 
            "om\n" + 
            "\n" + 
            "mpszxcfoniqtbyahlgv\n" + 
            "rjzakgwftcyiuldnxopsvq\n" + 
            "iohnmfyvatsblzxqpecg\n" + 
            "\n" + 
            "gbie\n" + 
            "zi\n" 
        ;
        
        // 1st part.
        int sum = 0;
        for (String group : groups.split("\n\n")) {
            sum += countDifferentQuestionsAnsweredByAnyone(group);
        }
        System.out.println(sum);
        //System.out.println(sum + " == 6565 ? => " + (sum == 6565));
        
        // 2nd part.
        sum = 0;
        for (String group : groups.split("\n\n")) {
            sum += countDifferentQuestionsAnsweredByAll(group);
        }
        System.out.println(sum);
    }
    
    public static int countDifferentQuestionsAnsweredByAnyone (String group) {
        HashSet<Character> answeredQuestions = new HashSet<Character>();
        
        for (String person : group.split("\n")) {
            for (int i = 0; i < person.length(); i++) {
                char question = person.charAt(i);
                
                if (!answeredQuestions.contains(question))  {
                    answeredQuestions.add(question);
                }
            }
        }
        
        return answeredQuestions.size();
    }
    
    public static int countDifferentQuestionsAnsweredByAll (String group) {
        ArrayList<Character> answeredQuestions = new ArrayList<Character>();
        HashMap<Character, Integer> count = new HashMap<Character, Integer>();
        
        String[] people = group.split("\n");
        for (String person : people) {
            for (int i = 0; i < person.length(); i++) {
                char question = person.charAt(i);
                
                if (!answeredQuestions.contains(question))  {
                    answeredQuestions.add(question);
                    count.put(question, 1);
                } else {
                    count.replace(question, answeredQuestions.get(question) + 1);
                }
            }
        }
        
        int sum = 0;
        for (int j = 0; j < answeredQuestions.size(); j++) {
            System.out.println(j + "/" + answeredQuestions.size());
            if (count.get(answeredQuestions.get(j)) == people.length) {
                sum++;
            }
        }
        
        return sum;
    }
    
    public static void test () {
        System.out.println("-------");
        System.out.println(" TESTS ");
        System.out.println("-------");
        
        String groups = 
            "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b\n"
        ;
        
        // 1st part.
        int count = countDifferentQuestionsAnsweredByAnyone(groups.split("\n\n")[0]);
        System.out.println(count + " == 3 ? => " + (count == 3));
        
        count = countDifferentQuestionsAnsweredByAnyone(groups.split("\n\n")[1]);
        System.out.println(count + " == 3 ? => " + (count == 3));
        
        count = countDifferentQuestionsAnsweredByAnyone(groups.split("\n\n")[2]);
        System.out.println(count + " == 3 ? => " + (count == 3));
        
        count = countDifferentQuestionsAnsweredByAnyone(groups.split("\n\n")[3]);
        System.out.println(count + " == 1 ? => " + (count == 1));
        
        count = countDifferentQuestionsAnsweredByAnyone(groups.split("\n\n")[4]);
        System.out.println(count + " == 1 ? => " + (count == 1));
        
        
        int sum = 0;
        for (String group : groups.split("\n\n")) {
            sum += countDifferentQuestionsAnsweredByAnyone(group);
        }
        System.out.println(sum + " == 11 ? => " + (sum == 11));
        
        System.out.println();
        
        // 2nd part.
        count = countDifferentQuestionsAnsweredByAll(groups.split("\n\n")[0]);
        System.out.println(count + " == 3 ? => " + (count == 3));
        
        count = countDifferentQuestionsAnsweredByAll(groups.split("\n\n")[1]);
        System.out.println(count + " == 0 ? => " + (count == 0));
        
        count = countDifferentQuestionsAnsweredByAll(groups.split("\n\n")[2]);
        System.out.println(count + " == 1 ? => " + (count == 1));
        
        count = countDifferentQuestionsAnsweredByAll(groups.split("\n\n")[3]);
        System.out.println(count + " == 1 ? => " + (count == 1));
        
        count = countDifferentQuestionsAnsweredByAll(groups.split("\n\n")[4]);
        System.out.println(count + " == 1 ? => " + (count == 1));
        
        
        sum = 0;
        for (String group : groups.split("\n\n")) {
            sum += countDifferentQuestionsAnsweredByAll(group);
        }
        System.out.println(sum + " == 6 ? => " + (sum == 6));
        
        
        System.out.println();
        System.out.println();
    }
    
    
}
